---
name: Devel-STDERR-Indent
version: 0.01
author: ~
abstract: Indents STDERR to aid in print-debugging recursive algorithms.
license: perl
requires:
  perl: >= 5.005
provides:
  Devel::STDERR::Indent:
    file: lib/Devel/STDERR/Indent.pm
    version: 0.01
generated_by: Module::Build version 0.2611
